var inOutt = [
    {
      id: 1,
      inOut: "2021-08-12",
      rubro: "Colectivo",
      importe: 100,
      trans: "E",
      tipo: "transporte",
    },
    {
      id: 2,
      inOut: "2020-01-15",
      rubro: "Alquiler",
      importe: 300,
      trans: "E",
      tipo: "vivienda",
    },
    {
      id: 3,
      inOut: "2020-12-30",
      rubro: "Sueldo",
      importe: 50000,
      trans: "I",
      tipo: "",
    },
    {
      id: 4,
      inOut: "2020-11-24",
      rubro: "Supermercado",
      importe: 101,
      trans: "E",
      tipo: "comida",
    },
    {
      id: 5,
      inOut: "2021-06-13",
      rubro: "Aguinaldo",
      importe: 18000,
      trans: "I",
      tipo: "",
    },
    {
      id: 6,
      inOut: "2021-01-11",
      rubro: "Perfume",
      importe: 1992,
      trans: "E",
      tipo: "varios",
    },
    {
      id: 7,
      inOut: "2021-03-01",
      rubro: "Changa",
      importe: 10113,
      trans: "I",
      tipo: "",
    },
    {
      id: 8,
      inOut: "2021-03-01",
      rubro: "Fruta",
      importe: 1033,
      trans: "E",
      tipo: "comida",
    },
    {
        id: 7,
        inOut: "2021-03-01",
        rubro: "Nafta",
        importe: 4113,
        trans: "E",
        tipo: "transporte",
      },
      {
        id: 7,
        inOut: "2021-03-01",
        rubro: "Colectivo",
        importe: 800,
        trans: "E",
        tipo: "transporte",
      },
      {
        id: 7,
        inOut: "2021-03-01",
        rubro: "Supermercado",
        importe: 5000,
        trans: "E",
        tipo: "comida",
      },
      {
        id: 7,
        inOut: "2021-03-01",
        rubro: "Remera",
        importe: 1313,
        trans: "E",
        tipo: "varios",
      },
      {
        id: 7,
        inOut: "2021-03-01",
        rubro: "Cortar Pasto",
        importe: 1423,
        trans: "I",
        tipo: "vivienda",
      },
      {
        id: 7,
        inOut: "2021-03-01",
        rubro: "luz",
        importe: 3000,
        trans: "E",
        tipo: "servicios",
      },
      {
        id: 7,
        inOut: "2021-03-01",
        rubro: "Cambiar Cerradura",
        importe: 600,
        trans: "e",
        tipo: "vivienda",
      },
      {
        id: 7,
        inOut: "2021-03-01",
        rubro: "Chips",
        importe: 200,
        trans: "E",
        tipo: "comida",
      },
      {
        id: 7,
        inOut: "2021-03-01",
        rubro: "Pepsi",
        importe: 200,
        trans: "E",
        tipo: "comida",
      },
      {
        id: 7,
        inOut: "2021-03-01",
        rubro: "Gimnasio",
        importe: 2200,
        trans: "E",
        tipo: "hobbies",
      },
  ];